# Generated by Django 5.0.1 on 2024-02-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.TextField(),
        ),
    ]
